# Generated by Django 5.2.8 on 2025-11-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='store_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
