# Generated by Django 5.2.5 on 2025-09-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_price_value_price_base_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='xbox_product_id',
            new_name='product_id',
        ),
    ]
