# Generated by Django 5.2.8 on 2025-11-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_slug_price_store_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
