# Generated by Django 5.2.5 on 2025-09-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_xbox_product_id_game_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
