# Generated by Django 5.2.8 on 2025-11-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='store_url',
        ),
    ]
