# Generated by Django 5.2.5 on 2025-09-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_developer_name_alter_game_publisher_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(),
        ),
    ]
