# Generated by Django 5.2.8 on 2025-11-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_price_store_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='price',
            name='is_on_sale',
        ),
    ]
