# Generated by Django 5.2.5 on 2025-10-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('product_id', models.CharField(blank=True, max_length=12, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.subscription'),
        ),
    ]
