# Generated by Django 5.2.5 on 2025-11-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_subscription_game_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('type', models.CharField(max_length=100)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('preview_image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.video'),
        ),
    ]
