# Generated by Django 5.2.5 on 2025-11-02 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_video_game_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='videos',
        ),
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('type', models.CharField(max_length=100)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('preview_image_url', models.URLField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='games.game')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
