# Generated by Django 5.2.5 on 2025-11-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_game_videos_gamevideo_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
